# --- Base stage ---
FROM node:20-alpine AS base
WORKDIR /app
COPY portafolio-frontend/package*.json ./

# Install dependencies separately for caching
RUN npm install

# Copy all files
COPY portafolio-frontend .

# Environment
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=1000
ENV WATCHPACK_POLLING=true
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

# Development mode (hot reload)
CMD ["npm", "run", "dev"]
